#!/bin/sh
# Regenerate nginx's Cloudflare allowlist, and reload only if it changed.
#
# The origin refuses anything that did not come through Cloudflare, which is
# what stops someone who has found the origin IP from forging CF-Connecting-IP
# and walking past the per-IP rate limit. That protection is only as current as
# this list: when Cloudflare adds a range and this file is stale, real visitors
# get a 403. Hence the timer.
#
# Fails closed on a bad fetch — an empty or truncated list would 403 everyone,
# so the old file is kept and the run reports failure.
set -eu

GEO=/etc/nginx/conf.d/cloudflare.conf
REALIP=/etc/nginx/snippets/cloudflare-realip.conf
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Cloudflare serves these without a trailing newline, which would run the last
# range into whatever the generator writes next. awk normalises that.
fetch() {
  curl -fsS --max-time 20 "https://www.cloudflare.com/ips-$1" | awk 'NF { print }'
}

fetch v4 >"$TMP/v4"
fetch v6 >"$TMP/v6"

# A plausible list is at least 20 ranges. Anything less is a truncated fetch or
# an error page that happened to return 200.
if [ "$(cat "$TMP/v4" "$TMP/v6" | grep -c '/')" -lt 20 ]; then
  echo "cloudflare-ips: implausibly short list, keeping the current one" >&2
  exit 1
fi

{
  echo "# Generated by refresh-cloudflare-ips.sh — do not edit."
  echo "#"
  echo "# \$realip_remote_addr is the address that actually opened the socket,"
  echo "# before real_ip rewrites \$remote_addr to the visitor. Matching on it is"
  echo "# what makes this an allowlist of Cloudflare rather than of visitors."
  echo "geo \$realip_remote_addr \$from_cloudflare {"
  echo "    default 0;"
  sed 's/^/    /; s/$/ 1;/' "$TMP/v4" "$TMP/v6"
  echo "}"
} >"$TMP/geo"

{
  echo "# Generated by refresh-cloudflare-ips.sh — do not edit."
  sed 's/^/set_real_ip_from /; s/$/;/' "$TMP/v4" "$TMP/v6"
  echo "real_ip_header CF-Connecting-IP;"
  echo "# Off: the header is a single address Cloudflare writes itself, not a"
  echo "# chain. Recursion would start trusting hops the caller can append."
  echo "real_ip_recursive off;"
} >"$TMP/realip"

if cmp -s "$TMP/geo" "$GEO" && cmp -s "$TMP/realip" "$REALIP"; then
  exit 0
fi

cp "$TMP/geo" "$GEO"
cp "$TMP/realip" "$REALIP"

# Validate before reloading. A bad generated file must not take the site down.
if ! nginx -t 2>/dev/null; then
  echo "cloudflare-ips: nginx -t failed after update" >&2
  exit 1
fi

nginx -s reload
echo "cloudflare-ips: updated and reloaded"
